const card = [
        {
        "id": 1994,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Miłość",
        "upgradesCnt": 6,
        "restartCnt": 0,
        "rarity": "d",
        "dere": "tsundere",
        "defence": 39,
        "attack": 42,
        "baseHealth": 41,
        "finalHealth": 88,
        "name": "Rin ",
        "characterUrl": "https://shinden.pl/character/11014",
        "source": "Stara baza",
        "animeTitle": "Shelter",
        "imageUrl": "https://cdn2.shinden.eu/1994.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/1994.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/1994.png",
        "ultimateQuality": "broken",
        "tags": [
        "Ulubione"
        ]
        },
        {
        "id": 8162,
        "isActive": true,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 27.94200091791153,
        "affection": "Obsesyjna miłość (α)",
        "upgradesCnt": 9,
        "restartCnt": 0,
        "rarity": "c",
        "dere": "raito",
        "defence": 61,
        "attack": 48,
        "baseHealth": 152,
        "finalHealth": 939,
        "name": "Archer of Red ",
        "characterUrl": "https://shinden.pl/character/69818",
        "source": "Safari",
        "animeTitle": "Fate/EXTRA",
        "imageUrl": "https://cdn2.shinden.eu/8162.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/8162.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/8162.png",
        "ultimateQuality": "broken",
        "tags": [
        "Ulubione",
        "Fate"
        ]
        },
        {
        "id": 8364,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Wrogość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "c",
        "dere": "deredere",
        "defence": 57,
        "attack": 63,
        "baseHealth": 137,
        "finalHealth": 114,
        "name": "Kayneth Archibald El-Melloi",
        "characterUrl": "https://shinden.pl/character/14600",
        "source": "Safari",
        "animeTitle": "Fate/Zero",
        "imageUrl": "https://cdn2.shinden.eu/8364.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/8364.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/8364.png",
        "ultimateQuality": "broken",
        "tags": [
        "Fate"
        ]
        },
        {
        "id": 18472,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Chłodność",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "mayadere",
        "defence": 67,
        "attack": 65,
        "baseHealth": 148,
        "finalHealth": 136,
        "name": "Norikata Emiya",
        "characterUrl": "https://shinden.pl/character/14605",
        "source": "Sklepik",
        "animeTitle": "Fate/Zero 2nd Season",
        "imageUrl": "https://cdn2.shinden.eu/18472.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/18472.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/18472.png",
        "ultimateQuality": "broken",
        "tags": [
        "Fate"
        ]
        },
        {
        "id": 20532452,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "d",
        "dere": "kamidere",
        "defence": 39,
        "attack": 46,
        "baseHealth": 193,
        "finalHealth": 164,
        "name": "Sage ",
        "characterUrl": "https://shinden.pl/character/87906",
        "source": "Sklepik",
        "animeTitle": "Goblin Slayer",
        "imageUrl": "https://cdn2.shinden.eu/20452.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/20452.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/20452.png",
        "ultimateQuality": "broken",
        "tags": [
        "Wymiana"
        ]
        },
        {
        "id": 282456249,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 6.213666890184085,
        "affection": "Wrogość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "deredere",
        "defence": 52,
        "attack": 71,
        "baseHealth": 127,
        "finalHealth": 101,
        "name": "Reika Rikudou",
        "characterUrl": "https://shinden.pl/character/77015",
        "source": "Sklepik",
        "animeTitle": "Fate/Apocrypha",
        "imageUrl": "https://cdn2.shinden.eu/28249.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/28249.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/28249.png",
        "ultimateQuality": "broken",
        "tags": [
        "Fate"
        ]
        },
        {
        "id": 343453180,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Obojętność",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "a",
        "dere": "deredere",
        "defence": 73,
        "attack": 77,
        "baseHealth": 113,
        "finalHealth": 113,
        "name": "Rao Si",
        "characterUrl": "https://shinden.pl/character/82535",
        "source": "Aktywność",
        "animeTitle": "Sheng Shi Zhuang Niang",
        "imageUrl": "https://cdn2.shinden.eu/34180.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/34180.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/34180.png",
        "ultimateQuality": "broken",
        "tags": [
        "Wymiana"
        ]
        },
        {
        "id": 3687231,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 366456871,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 32346871,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 36534334871,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 36852371,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 36835271,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 3643871,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 36833371,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 3682271,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 36871111,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 3687111,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        },
        {
        "id": 368711,
        "isActive": false,
        "isInCage": false,
        "isTradable": true,
        "isUnique": false,
        "isUltimate": false,
        "expCnt": 0,
        "affection": "Złośliwość",
        "upgradesCnt": 2,
        "restartCnt": 0,
        "rarity": "b",
        "dere": "kuudere",
        "defence": 67,
        "attack": 64,
        "baseHealth": 73,
        "finalHealth": 62,
        "name": "Ellen ",
        "characterUrl": "https://shinden.pl/character/82353",
        "source": "Karta+",
        "animeTitle": "Tensei Shitara Slime Datta Ken",
        "imageUrl": "https://cdn2.shinden.eu/36871.png",
        "smallImageUrl": "https://cdn2.shinden.eu/small/36871.png",
        "profileImageUrl": "https://cdn2.shinden.eu/profile/36871.png",
        "ultimateQuality": "broken",
        "tags": [
        "Slime"
        ]
        }
    ]


export default card